### ISSUE TITLE
Words Exposed through Unencrypted HTTP Response

### ISSUE THREAD

**Issue by mrigankpawagi** [Gizmo-Rishab/Hangman-Game#3]
![image](https://user-images.githubusercontent.com/25179158/87066450-39133400-c230-11ea-953f-6c5d3a5b2663.png)
Hi Rishabh,
I am impressed by your game and its simple, sleek design. I was just playing around a bit (won quite a few times) when I figured out a potential source of exploitation on the website. It doesn't matter much for a game, but you can learn a few things if you pay attention to it.
All I had to do was to open the network panel and look at the HTTP responses to view the words (and possibly cheat). I had like to know your ideas about fixing this.

Regards.

**Comment by retro-sapphire** [comment]
Hi Mrigank,
Sorry for the late response, and thanks for trying out my project. For some reason I got the email about this github issue being opened today, even though the issue was reported in 2020. I made the project back when I was learning NodeJS, and I'll see what I can do to fix the issue cus I'm busy with studies right now. Thanks once again for reporting!
